### PR TITLE
Create a Visual Studio Code extension

### PR DESCRIPTION
**Pull request by jasononeil**
Hi @Gama11 - this is amazing work, really nice!

I wanted to use this with "format on save" in visual studio code, so have started the work necessary to make it an extension.

- I had to change how errors are logged, as I was receiving a compile error earlier
- I added hxml files, as I'm more familiar with working with these. I can remove if desired
- I added the boilerplate to generate the extension and run it in debug mode. You run the project from the "Debug" tab in VSCode, and it will launch a new window with the autoformatter active. (You may have to configure formatOnSave to be turned on for your workspace)

Would you be interested in merging this or publishing it? It might also be good to include it in the main vshaxe extension, but that would require more co-ordination between repos. When I considered that, I thought having two extensions to install isn't that bad :)

### CODE REVIEW

**Comment by jasononeil** [comment]
(p.s. I'm also working on some line wrapping for array and object declarations over a certain length, but will put in a separate PR)

**Comment by Gama11** [comment]
While I'm happy somebody else is excited about code formatting, I now wish I had written a readme to save you this work. :) Here's the deal: this is already integrated in vshaxe / haxe-languageserver, but locked behind `#if debug`:

https://github.com/vshaxe/haxe-languageserver/blob/d7799fa0570b91f10ec272ee4e7287f0224acf09/src/haxeLanguageServer/Context.hx#L257-L259

So if you [install vshaxe from source](https://github.com/vshaxe/vshaxe/wiki/Installation#from-source) and make a debug build, you can use the formatter.

I consider this project more of an unfinished experiment... The approach I took with using a parse tree means the formatter will never be able to deal with conditional compilation properly, see also the thoughts I wrote down [here](https://community.haxe.org/t/status-of-vscode-extension-for-formatter-and-checkstyle/608).

Recently I've been wondering if we could use @AlexHaxe's [tokentree library](https://github.com/HaxeCheckstyle/tokentree). This would be similar to clang-format, which is also based on tokens rather than a proper parse tree, it seems, and is able to deal with conditional compilation as a result. Right now I don't really have time for that though.

**Comment by jasononeil** [comment]
Hahaha no worries. Thanks for the explanation! And sorry I missed the discussion thread.

Would you be interested in a PR that makes the formatter available behind a setting, rather than requiring a debug build? I understand if you'd prefer to keep it hidden until a more complete implementation is available.

**Comment by Gama11** [comment]
Maybe we could have an undocumented setting for it... Like you guessed, I don't really want people to start relying on this too much yet and switch over their projects, since it's not the "proper solution" I'm hoping is going to exist one day.

How usable have you found it so far in practice?

Also, nice to see you getting back to some Haxe dev. ;)

**Comment by jasononeil** [comment]
Thanks! I don't use Haxe at my current job (mostly react+flow and some elm), but I still love using it for side projects.

I'll take a look at tokentree, I've gotten really attached to prettier, elm-fmt and go-fmt and don't want to have to format my own code anymore :) This project worked on simple things I tried, but it looks like tokentree has some fault tolerance as well, which might be good to include

**Comment by AlexHaxe** [comment]
Since there is a certain amount of overlap between a checkstyle and a formatter tool, it might make sense to build some kind of common API / layer, so that both have the same information and can make decisions based on identical data.
e.g. haxe-checkstyle has an indentation check based on tokentree. It operates in two stages:
1. gather information and build a model of ideal indentation per line
2. compare model with reality

The model currently has three arrays with one entry per line each. One just holds indentation levels, one holds excluded lines (comments, multiline strings) and the third holds lines of wrapped code. 

Tokentree doesn't store whitespace and has no concept of line numbers, all position are byte offsets calculated from file start.

**Comment by AlexHaxe** [comment]
I've built an initial version of a tokentree based formatter: https://github.com/HaxeCheckstyle/tokentree-formatter

There are quite a few things missing, most of them should be fairly easy. 
Building a VSCode extension around it should also work and would be able support full or partial formatting (line based).

**Comment by Gama11** [comment]
A few months later, we now have a working haxe formatter! \o/

- https://community.haxe.org/t/new-formatter-haxelib-library/987
- https://github.com/vshaxe/vshaxe/wiki/Formatting

I'm going to mark this repo as "archived".

**Pull request closed without merging**
